import { Inter } from "next/font/google";
import "./globals.css";
import { getGlobalData } from "@/data/loaders";
import { Header } from "@/components/custom/Header";
import { Footer } from "@/components/custom/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const globalData = await getGlobalData();
  console.log(globalData);
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header data={globalData.header} />
        <div>
        {children}
        </div>
        <Footer data={globalData.footer} />
        
        </body>
    </html>
  );
}
